---
title: "Supplementary Information"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'poster_SI.html'))})
author: "Autumn Mcknite"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Load libraries

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```


## Fentanyl

```{r echo=FALSE}
plot_df = read.csv("./Fentanyl/fentanyl_stats.csv")
plot_df$age <- factor(plot_df$age,
                      levels = c("Neonatal\n(1.2 mcg/hr/kg)",
                                 "Infant\n(0.6 mcg/hr/kg)",
                                 "Child\n(0.6 mcg/hr/kg)", 
                                 "School Age\n(0.6 mcg/hr/kg)",
                                 "Adolescent\n(0.6 mcg/hr/kg)"))


alpha_vals = c(0.99, 0.5, 0.2)
p1 = plot_df %>%
  ggplot(aes(age)) +
  geom_hline(yintercept = c(0.6, 3), linewidth = 2, col = 'lightgrey') +
  geom_boxplot(
    aes(ymin = y05, lower = y25, middle = y50, upper = y75, ymax = y95, fill = age),
    stat = "identity", show.legend = FALSE
  ) + 
  scale_y_continuous(expression(Concentration~ng~ml^-1)) +
  scale_x_discrete("", guide = guide_axis(angle = 45)) +
  scale_alpha_manual(values = alpha_vals) +
  theme_bw() +
  theme(text=element_text(size=14))

print(p1)
```

## Midazolam

```{r echo=FALSE}
plot_df = read.csv("./Midazolam/midazolam_stats.csv")
plot_df$age <- factor(plot_df$age,
                      levels = c("Neonatal\n(0.04 mcg/hr/kg)",
                                 "Infant\n(0.18 mcg/hr/kg)",
                                 "Child\n(0.18 mcg/hr/kg)", 
                                 "School Age\n(0.18 mcg/hr/kg)",
                                 "Adolescent\n(0.18 mcg/hr/kg)"))

alpha_vals = c(0.99, 0.5, 0.2)
p1 = plot_df %>%
  ggplot(aes(age)) +
  geom_hline(yintercept = c(200, 1000), linewidth = 2, col = 'lightgrey') +
  geom_boxplot(
    aes(ymin = y05, lower = y25, middle = y50, upper = y75, ymax = y95, fill = age),
    stat = "identity", show.legend = FALSE
  ) + 
  scale_y_continuous(expression(Concentration~ng~ml^-1)) +
  scale_x_discrete("", guide = guide_axis(angle = 45)) +
  scale_alpha_manual(values = alpha_vals) +
  theme_bw() +
  theme(text=element_text(size=14))

print(p1)
```
